[package]
name = "emlop"
version = "0.3.1"
description = "A fast, accurate, ergonomic emerge.log parser"
keywords = ["gentoo", "portage", "emerge"]
categories = ["command-line-utilities", "parsing"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/vincentdephily/emlop"
repository = "https://github.com/vincentdephily/emlop"
authors = ["Vincent de Phily <moltonel@gmail.com>",
           "Illia Shestakov <ishestakov@airmail.cc>"]
edition = "2018"

[dependencies]
ansi_term = "~0.11"
atty = "~0.2"
chrono = "~0.4"
chrono-english = "~0.1"
clap = "~2.33"
failure = "~0.1"
failure_derive = "~0.1"
log = "~0.4"
regex = "~1.1"
stderrlog = "~0.4"
sysconf = "~0.3"
crossbeam-channel = "~0.3"

[dependencies.tabwriter]
features = ["ansi_formatting"]
version = "~1.1"

[dev-dependencies]
assert_cli = "~0.6"

[profile.release]
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
lto = true
