[package]
authors = ["Vincent de Phily <vincent.dephily@mobile-devices.fr>"]
name = "emlop"
version = "0.1.0"

[dependencies]
chrono = "~0.4"
clap = "~2.29"
regex = "~0.2"
sysconf = "~0.3"
[profile.release]
debug = false
debug-assertions = false
lto = true
