[package]
name = "emlop"
version = "0.4.0"
description = "A fast, accurate, ergonomic emerge.log parser"
keywords = ["gentoo", "portage", "emerge"]
categories = ["command-line-utilities", "parsing"]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "https://github.com/vincentdephily/emlop"
repository = "https://github.com/vincentdephily/emlop"
authors = ["Vincent de Phily <moltonel@gmail.com>",
           "Illia Shestakov <ishestakov@airmail.cc>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.32"
atty = "0.2.14"
chrono = "~0.4"
chrono-english = "~0.1"
clap = "2.33.3"
log = "0.4.11"
regex = "1.3.9"
stderrlog = "0.5.0"
sysconf = "~0.3"
crossbeam-channel = "0.5.0"

[dependencies.tabwriter]
features = ["ansi_formatting"]
version = "1.2.1"

[dev-dependencies]
assert_cmd = "1.0.1"
escargot = "0.5.0"
lazy_static = "1.4.0"

[profile.release]
debug = false
debug-assertions = false
codegen-units = 1
incremental = false
lto = true
