[package]
authors = ["Vincent de Phily <moltonel@gmail.com>"]
name = "emlop"
version = "0.1.0"

[dependencies]
atty = "~0.2"
chrono = "~0.4"
clap = "~2.29"
regex = "~0.2"
sysconf = "~0.3"
tabwriter = "~1.0"
[profile.release]
debug = false
debug-assertions = false
lto = true
