[package]
authors = ["Vincent de Phily <moltonel@gmail.com>"]
name = "emlop"
version = "0.2.0"

[dependencies]
ansi_term = "~0.11"
atty = "~0.2"
chrono = "~0.4"
chrono-english = "~0.1"
clap = "~2.31"
failure = "~0.1"
failure_derive = "~0.1"
log = "~0.4"
regex = "~0.2"
stderrlog = "~0.3"
sysconf = "~0.3"

[dependencies.tabwriter]
features = ["ansi_formatting"]
version = "~1.0"

[dev-dependencies]
assert_cli = "~0.5"
indoc = "~0.2"

[profile.release]
debug = false
codegen-units = 1
debug-assertions = false
incremental = false
lto = true
